[황석영] : 로그인 기능 로직 수정 및 contextAPI 추가
willy4202/puzzle-ai-fronted-32th pull request #10
Opened 2022-05-30 08:38 UTC by willy4202

## :: 최근 작업 주제
- [x] 기능 추가
- [ ] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정
<br />

## :: 구현 목표 

1. 로그인 페이지 기능 구현
- 백엔드 데이터 통신
- 토큰 저장 후, 네비게이션 적용

<br />

## :: 세부 내용

1. state로 유저 email, pw 전송

2.  유효성 검사 통과 후, asyncStorge에 cookie 저장 후 main screens로 이동

3. 비밀번호 전환 기능
- 비밀번호 인풋창의 눈 아이콘을 클릭할시 `secureTextEntry={}`의 요소를 true, false로 전환해
어떤 비밀번호를 입력했는지 내용을 확인할 수 있습니다.

## 질문 사항

1. 전달주신 공식문서 바탕으로 useContext, useReducer 활용해서 작성했습니다. 검토 부탁드립니다.

2022-05-30 08:56 UTC, jasonkang14 commented on App.tsx
> +            {userState.isLogIn ? (
굳굳 best입니다. 공식문서 보는 것 같네요. 고생하셨습니다! 💯

2022-05-30 08:56 UTC, jasonkang14 commented on src/AuthContext.tsx
> +  userState: {isLogIn: false, isLoading: true},
`isLoading` state 추가 좋습니다 👍

2022-05-30 08:56 UTC, jasonkang14 commented on src/AuthContext.tsx
> +        isLogIn: true,
`loading` 은 변화되지 않나요?

2022-05-30 09:05 UTC, willy4202 commented on src/AuthContext.tsx
> +        isLogIn: true,
앗,,, 바로 로직 추가해서 푸쉬해두겠습니다! :)

2022-05-30 11:57 UTC, jasonkang14 requested changes

2022-05-30 11:57 UTC, jasonkang14 commented on src/AuthContext.tsx
> +import {config} from '@screens/../config';
여기는 경로가 좀 이상하네요 갑자기 중간에 .. 이 들어가는 부분을 수정 부탁 드립니다

2022-05-30 11:57 UTC, jasonkang14 commented on src/AuthContext.tsx
> +      console.log(checkToken);
console.log()를 제거해주세요

2022-05-30 11:57 UTC, jasonkang14 commented on App.tsx
> +    isLoaded();
isLoaded는 왠지 Boolean 값 일 것 같은 변수명입니다. 
제가 이해한 loading 변수의 역할은 
Api 통신이 이루어질 때 true로 변했다가 서버로부터 response를 받거나 에러가 발생하면 false로 변경되는 것을 생각했는데요. 

현업에서는 위와 같은 방식으로 클라이언트가 여러번 버튼을 클릭해서 중복 요청을 보내는 것을 방지하기 위해 사용됩니다. 

같은 이유로 회원가입 요청을 할 때도 loading 이라는 변수는 사용될 것 같으니
loading의 초기값은 false로 두고 통신이 시작할 때 상태를 loading : true로 변경하고, 통신이 종료되면 loading : false로 변경하는 방식이 좋을 것 같습니다.

2022-05-30 14:19 UTC, willy4202 commented on src/AuthContext.tsx
> +import {config} from '@screens/../config';
넵 수정했습니다! :)

2022-05-30 14:19 UTC, willy4202 commented on src/AuthContext.tsx
> +      console.log(checkToken);
넵 반영했습니다!!

2022-05-30 14:20 UTC, willy4202 commented on App.tsx
> +    isLoaded();
넵 감사합니다! :) 덕분에 방향성을 더 구체적으로 잡을 수 있을 듯 합니다!

자세한 사항 정리해서 31일 화요일에 질문 드리겠습니다,,!

2022-05-31 05:08 UTC, jasonkang14 approved these changes
LGTM

2022-05-31 05:08 UTC, merged