[황석영] 진료예약 스크린 레이아웃 작업
willy4202/puzzle-ai-fronted-32th pull request #11
Opened 2022-05-31 06:09 UTC by willy4202

## :: 최근 작업 주제
- [x] 기능 추가
- [ ] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정
<br />

## :: 구현 목표 

1.진료 예약 스크린 구현

<br />

## :: 세부 내용

1. 작업의 용이성을 위해 레이아웃부터 작업했습니다.
2. 항목마다 컴포넌트화 진행해 유지보수의 용이성을 확보하고자 했습니다.
3. 이미지 레이아웃은 기능과 동시에 진행할 예정입니다.

2022-06-01 09:04 UTC, jasonkang14 requested changes

2022-06-01 09:04 UTC, jasonkang14 commented on src/screens/MakeREZ/MakeREZ.tsx
> +import SymptomView from './SymptomView/SymptomView';
파일 이름을 index.tsx로 하면  import 경로를 하나 단축할 수 있습니다.

2022-06-01 09:04 UTC, jasonkang14 commented on src/screens/MakeREZ/MakeREZ.tsx
> +import {HomeStackParamList} from '~/../App';
중간에 `..` 이 들어가는 부분을 수정해주세요

2022-06-01 09:04 UTC, jasonkang14 commented on src/screens/MakeREZ/MakeREZ.tsx
> +import {} from 'react-native';
import하는 패키지가 없는 라인은 삭제해주세요

2022-06-01 09:04 UTC, jasonkang14 commented on src/screens/MakeREZ/TimeView/TimeView.tsx
> +  margin: 0 18px 0 18px;
여기도 margin-horizontal 적용이 가능합니다.

2022-06-01 13:53 UTC, willy4202 commented on src/screens/MakeREZ/ImagePicker/ImagePicker.tsx
> +  margin: 0 18px 0 18px;
넵 감사합니다! 바로 적용해두겠습니다!

2022-06-01 13:53 UTC, willy4202 commented on src/screens/MakeREZ/MakeREZ.tsx
> +import SymptomView from './SymptomView/SymptomView';
아하,,! 꼭 폴더명과 같은 이름을 쓸 필요는 없겠군요,,!

2022-06-01 13:54 UTC, willy4202 commented on src/screens/MakeREZ/MakeREZ.tsx
> +import {} from 'react-native';
넵 확인했습니다 :) !!

2022-06-01 13:55 UTC, willy4202 commented on src/screens/MakeREZ/TimeView/TimeView.tsx
> +  margin: 0 18px 0 18px;
넵 감사합니다 마찬가지로 적용했습니다! :)

2022-06-02 04:39 UTC, jasonkang14 requested changes

2022-06-02 04:39 UTC, jasonkang14 commented on src/screens/MakeREZ/SymptomView/index.tsx
> +        <SymptomInput multiline={true} placeholder="증상을 입력해주세요" />
prop으로 true를 넘겨줄 때는 아래와 같이 생략할 수 있습니다.
```typescript
<SymptomInput multiline placeholder="증상을 입력해주세요" />
``` 

[airbnb coding convention](https://github.com/airbnb/javascript/tree/master/react#props) 을 참고해주세요

2022-06-02 05:45 UTC, jasonkang14 approved these changes
LGTM

2022-06-02 05:45 UTC, merged