정덕우 / 날짜선택기능 추가
willy4202/puzzle-ai-fronted-32th pull request #15
Opened 2022-06-01 07:06 UTC by jungdeokwoo

## :: 최근 작업 주제
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정
<br />

## :: 구현 목표 

의사 스케쥴화면의 달력에서 날짜 선택기능 완료

[](https://user-images.githubusercontent.com/97271725/171346138-508cd460-3e5b-4f5b-ac4f-7364fd180e8b.mp4)

<br />

## :: 세부 내용

1. 해당월의 전체 날짜데이터로 map을 사용해서 날짜를 만들어줄때 날짜데이터를 달력의 날짜 컴포넌트에 전달해줍니다.
2. 날짜를 눌렀을때 함수로 날짜 데이터를 전송해서 setState를 이용하여 날짜 정보를 state값에 저장해줍니다.
3. 저장된 state 값(날짜데이터 year,month,date,day)의 date의 값과 달력에 표시된 날짜값이 동일하면 isChecked가 true가 되도록 설정(기본값은 false)
4. isChecked가 true일때 스타일이 변경되도록 하여 선택한 날짜의 글자와 배경이 달라지도록 하였습니다.
5. 날짜를 눌렀을때 함수로 date 값만 저장되도록 하였는데 추후에 백엔드와 통신할때 날짜정보를 전송하기 수월하도록  전체데이터(year,month,date,day)값을 모두 state에 저장하도록 하였습니다.

2022-06-01 15:23 UTC, jasonkang14 requested changes

2022-06-01 15:23 UTC, jasonkang14 commented on src/SelectContext.tsx
> +export const SelectContext = createContext<SelectProps>({
날짜를 보여줄 화면이 많으니 전역변수로 뺀 것은 좋은 선택입니다 👍

2022-06-01 15:23 UTC, jasonkang14 commented on src/components/Calendar.tsx
> +        {calendarDate.slice(0, 7).map((date: NewDate, idx: number) => (
이전 PR의 comment와 유사하게 array로만 map을 하면 굳이 `.slice()`를 하지 않아도 될 것 같습니다. 
아니면 슬랙으로 안내드린 `FlatList`속성을 사용하셔도 될 것 같고요

2022-06-01 15:23 UTC, jasonkang14 commented on src/components/CalendarButton.tsx
> +  type?: string;
type도 구체적으로 적어주시는 편이 좋습니다. 
date인지, 아니면 다른 prop이 잇다면 적어주시는 편이 좋습니다. 
그런데 해당 prop의 목적이 무엇인가요? 코드에서 사용되는 부분이 없는 것 같습니다.

2022-06-02 08:13 UTC, jungdeokwoo commented on src/components/Calendar.tsx
> +        {calendarDate.slice(0, 7).map((date: NewDate, idx: number) => (
감사합니다!

2022-06-02 08:14 UTC, jasonkang14 requested changes

2022-06-02 08:14 UTC, jasonkang14 commented on App.tsx
> +            {!userState.isLogIn ? (
느낌표 빠져야 하지 않나요?

2022-06-02 08:14 UTC, jasonkang14 commented on src/ReservationContext.tsx
> +  selectDate: {
👍

2022-06-02 08:14 UTC, jasonkang14 commented on src/components/CalendarButton.tsx
> +  type?: string;
comment확인 부탁 드립니다

2022-06-02 08:14 UTC, jasonkang14 commented on src/screens/DocScheme/DocScheme.tsx
> +          <PrevIcon overlap={true} source={Prev} />
prop으로 넘겨주는 값이 true인 경우 따로 적어주지 않아도 됩니다. 
[airbnb coding convention](https://github.com/airbnb/javascript/tree/master/react#props)을 참고해주세요

2022-06-02 08:17 UTC, jungdeokwoo commented on src/components/CalendarButton.tsx
> +  type?: string;
달력에서 요일도 같은 컴포넌트를 활용하고 있어서 달력의 날짜와 요일이 스타일이 다르기때문에 type이 week인 경우에는 글자색이 바뀌도록 설정해두었습니다!

2022-06-02 08:20 UTC, jungdeokwoo commented on App.tsx
> +            {!userState.isLogIn ? (
작업화면을 띄우려고 잠깐 세팅해놓은건데 깜빡했습니다 수정하였습니다!

2022-06-02 08:20 UTC, jungdeokwoo commented on src/screens/DocScheme/DocScheme.tsx
> +          <PrevIcon overlap={true} source={Prev} />
넵 감사합니다!

2022-06-02 08:53 UTC, jasonkang14 approved these changes
LGTM

2022-06-02 08:53 UTC, merged