Feature/signup function
willy4202/puzzle-ai-fronted-32th pull request #7
Opened 2022-05-27 09:07 UTC by jungdeokwoo

## :: 최근 작업 주제
- [x] 기능 추가
- [] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정
<br />

## :: 구현 목표 

1. 회원가입 시 이름, 이메일, 비밀번호에 대한 유효성 평가,
2. 비밀번호 입력란 우측의 아이콘을 눌렀을때 비밀번호가 보이게 또는 안보이게 설정.
3. 유효성을 모두 통과하였을때만 버튼 활성화

<br />

## :: 세부 내용
- 이메일 중복 검사시, 바로바로 통신을 통해 PATCH로 보내는 형식이 아닌, 입력 후 0.8초 후에 통신을 보내 적합여부를 확인할 수 있게
useEffect와 setTimeout/clearTimeout을 이용하여 디바운스를 적용하였습니다.

- 각 유효성 검사는 변수로 지정하여 비밀번호 같은 경우는 정규표현식을 통해 적합성 여부를 판별하였고, 비밀번호와 비밀번호 확인같은 경우는 입력값이 있을때만 유효성 검사가 되도록 조건을 걸어주었습니다.

- type.ts 파일을 생성하여 각 컴포넌트에 쓰이는 인터페이스타입들을 type파일 안에서 관리하고 import 해오는 식으로 처리하였습니다.

<br />

## :: 질문 사항
디바운싱을 컴포넌트 재활용을 하다보니 이벤트 핸들러를 컴포넌트 안에서 사용하게 되어 useEffect 를 활용하여 진행하였는데 통신할때는 크게 문제 없이 작동하긴 했었는데 혹시 잘못된 방식인가요??

사실 크게 상관은 없기는 한데 비밀번호 아이콘으로 on/off 기능을 구현할때 무언가를 켜고 끄는 기능이 나중에 또 필요할까봐서 customHook을 사용해서 Toggle Hook을 만들어서 적용하려 했는데 그때 시뮬레이터에서 무분별한 랜더링이 일어나는 문제가 생길 수 있다고 오류메세지가 떴었는데 커스텀훅을 적용을 할 수 없는걸까요?

이메일 중복 유효성 검사에서 처음에는 isEmailValid 변수를 지정하고  fetch를 통한 결과로 성공일때는 isEmailValid 를 true 값으로, 중복된 경우에는 isEmailValid를 false로 두었었는데 단순 변수로 지정하였을때는 화면의 변화나 console값의 변화가 없어서 state값으로 변경시켜주었는데  단순변수이기때문에 랜더링이 되지 않기때문에 이메일중복오류메세지가 뜨지 않았던건지 아니면 fetch후 then. 구문에서는
ex) .then(res=> if(res.message){ isEmailValid = true} 와 같이 재할당 자체가 되지 않는것인지 궁금합니다.

npm run ios 할때마다 시뮬레이터 실행은 잘 되는데.. Warning 이 많이 뜨면서.. dev tools 가 나타나질 않습니다, Warning 뜨는거 무시하고 작업을 해도 괜찮은지 아니면 Warning 문제를 다 해결해주고 작업을 해야하는지.. 여쭤보고 싶습니다.(혹시나 나중에 문제가 될 수 있을까봐...)

2022-05-27 10:19 UTC, willy4202 reviewed
역시 덕우님입니다,,! 코드를 보다 몇가지 궁금증이 생겨서 적어뒀어요!! 
시간 나실때 답변해주시면 큰 도움 될 것 같습니다. 
감사합니다 👍  :)

2022-05-27 10:19 UTC, willy4202 commented on src/screens/Signup/Signup.tsx
> +  }, [inputData.email]);
이거 로직 너무 신기하네요,,! 어떤 기능을 하는건가요? 
노드로 setTimeout 같은 기능을 구현한 것 같은데,
email validation 체크 하는데 시간을 소요하는 이유가 궁금해요,,!

2022-05-27 10:19 UTC, willy4202 commented on src/types/type.ts
> +  setInputData: Dispatch<SetStateAction<Data>>;
setState의 타입을 void로 지정해주는 게아니라 
`Dispatch<SetStateAction<Data>>`해당 타입을 넘기는 이유가
`setInputData`가 해당 타입을 모두 핸들링하기 때문인가요?
저도 setState를 props으로 던질땐 이렇게 해봐야겠어요 

너무 신기하네요,,,!

2022-05-28 03:58 UTC, jungdeokwoo commented on src/screens/Signup/Signup.tsx
> +  }, [inputData.email]);
값이 입력될때마다 서버로 fetch를 계속 보내면 효율적이지 못하고 나중에 유료 API를 쓰게되면 비용이 감당못할정도로 많이 나온다고 해서 setTimeout으로 일정시간(지금은 0.8초) 후에 통신이 되도록 하고, 그 전에 다시 입력을 하게되면 clearTimeout으로 Timeout 함수를 리셋시켜서 통신이 되지 않도록 하는 기능입니다 /// 디바운스 찾아보시면 잘 설명되있더라구요ㅎ

2022-05-28 04:00 UTC, jungdeokwoo commented on src/types/type.ts
> +  setInputData: Dispatch<SetStateAction<Data>>;
setState의 타입으로 void만 지정을 해주니까 나중에 setState에 값을  입력했을때 그 값들의 형식이 일치하지 않아서 에러가 나오더라구요 그래서 찾아보니깐 setState는 기본적으로 형식을 저렇게 넣어준다고 해서 저렇게 입력해놓고 그 안에 입력되는 값의 형식 자체가 Data 타입이라서 저렇게 넣어두었습니다~

2022-05-29 15:39 UTC, jasonkang14 requested changes

2022-05-29 15:39 UTC, jasonkang14 commented on src/components/LoginSignupBtn.tsx
> +      <LoginBtn disabled={isDisable} onPress={() => postData()}>
이런경우는 변수명을 맞춰주는 편이 좋습니다. 
```typescript
<LoginBtn disabled={disabled} onPress={() => postData()}/>
```

2022-05-29 15:39 UTC, jasonkang14 commented on src/components/PasswordWrapper.tsx
> -import React from 'react';
`PasswordWrapper`를 따로 만드는 편이 훨씬 좋아보이네요 👍

2022-05-29 15:39 UTC, jasonkang14 commented on src/screens/Signup/Signup.tsx
> +  const [inputData, setInputData] = useState<Data>({
변수명은 `data`라는 일반적인 이름보다는 `SignupData`, `UserData` 등과 같이 구체적으로 선언해주는 편이 가독성에 유리합니다.

2022-05-29 15:39 UTC, jasonkang14 commented on src/screens/Signup/Signup.tsx
> +    if (!!inputData.email) {
조건 처리 좋습니다 👍

2022-05-29 15:39 UTC, jasonkang14 commented on src/screens/Signup/Signup.tsx
> +  const postData = () => {
`DATA` 라는 타입과 유사하게, `postData`도 `postSignUp`과 같이 조금 더 구체적으로 작성하시는 편이 가독성에 좋습니다.

2022-05-29 15:45 UTC, jasonkang14 commented
1. 디바운싱을 컴포넌트 재활용을 하다보니 이벤트 핸들러를 컴포넌트 안에서 사용하게 되어 useEffect 를 활용하여 진행하였는데 통신할때는 크게 문제 없이 작동하긴 했었는데 혹시 잘못된 방식인가요??
- `useDebounce`는 제대로 작동할 것 같아 보입니다. 
- 작성하신 것처럼 `effect hook`을 사용하는 것이 일반적입니다. 

2. 사실 크게 상관은 없기는 한데 비밀번호 아이콘으로 on/off 기능을 구현할때 무언가를 켜고 끄는 기능이 나중에 또 필요할까봐서 customHook을 사용해서 Toggle Hook을 만들어서 적용하려 했는데 그때 시뮬레이터에서 무분별한 랜더링이 일어나는 문제가 생길 수 있다고 오류메세지가 떴었는데 커스텀훅을 적용을 할 수 없는걸까요?
- 커스텀을 적용할 수는 있는데 dependency에 문제가 있는게 아닐까 생각합니다. 
- 왠지 state를 effect hook의 dependency에 넣고, 그 effect hook안에서 setState()하지 않았을까 생각합니다. 
- 다른데서 쓰일 것 같은 기능을 커스텀훅으로 만드는 것은 좋은 습관인데, on/off정도는 state하나라서 굳이 커스텀 훅까지 사용할 필요는 없어보입니다. 
- 오히려 디바운싱을 `useDebounce()`라는 커스텀 훅으로 작업하시는 편이 로직이 길기때문에 가독성과 추상화라는 컨셉에서 더 좋아보입니다. 

3. 이메일 중복 유효성 검사에서 처음에는 isEmailValid 변수를 지정하고 fetch를 통한 결과로 성공일때는 isEmailValid 를 true 값으로, 중복된 경우에는 isEmailValid를 false로 두었었는데 단순 변수로 지정하였을때는 화면의 변화나 console값의 변화가 없어서 state값으로 변경시켜주었는데 단순변수이기때문에 랜더링이 되지 않기때문에 이메일중복오류메세지가 뜨지 않았던건지 아니면 fetch후 then. 구문에서는
ex) .then(res=> if(res.message){ isEmailValid = true} 와 같이 재할당 자체가 되지 않는것인지 궁금합니다.
- 화면에 변화가 없었던 것은 말씀하신 것처럼 state가 아니라서 render가 일어나지 않았기 때문입니다. 
- console값에 변화는 console의 위치가 어디인지에 따라 다를 것 같습니다. 
- `.then(res=> if(res.message){ isEmailValid = true}` 이런식의 작성은 가능합니다. 

4. npm run ios 할때마다 시뮬레이터 실행은 잘 되는데.. Warning 이 많이 뜨면서.. dev tools 가 나타나질 않습니다, Warning 뜨는거 무시하고 작업을 해도 괜찮은지 아니면 Warning 문제를 다 해결해주고 작업을 해야하는지.. 여쭤보고 싶습니다.(혹시나 나중에 문제가 될 수 있을까봐...)
- warning은 일반적으로 무시하셔도 됩니다

2022-05-30 03:24 UTC, jasonkang14 approved these changes
LGTM

2022-05-30 03:25 UTC, merged